version: "3.3"
services:
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis
    ports:
      - "6379:6379"
  order_service:
    build:
      context: .
      dockerfile: order_service/Dockerfile
      # note that context is project root folder, not service folder.
      #  It's done consciously because we need to copy app_common folder from project root
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=.
      - FLASK_DEBUG=1
      - CELERY_BROKER=pyamqp://rabbitmq:rabbitmq@rabbit//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbit
      - redis
    volumes:
      - ./order_service/order_service:/code/order_service
  order_service_asyncapi_docs_server:
    build:
      context: ./order_service
      dockerfile: asyncapi_docs_server.Dockerfile
    command: http-server ./asyncapi_html
    ports:
      - "8081:8080"
  consumer_service_worker:
    build:
      context: .
      dockerfile: consumer_service/Dockerfile
      # note that context is project root folder, not service folder.
      #  It's done consciously because we need to copy app_common folder from project root
    environment:
      - PYTHONPATH=.
      - CELERY_BROKER=pyamqp://rabbitmq:rabbitmq@rabbit//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbit
      - redis
  consumer_service_asyncapi_docs_server:
    build:
      context: ./consumer_service
      dockerfile: asyncapi_docs_server.Dockerfile
    command: http-server ./asyncapi_html
    ports:
      - "8082:8080"
  restaurant_service_worker:
    build:
      context: .
      dockerfile: restaurant_service/Dockerfile
      # note that context is project root folder, not service folder.
      #  It's done consciously because we need to copy app_common folder from project root
    environment:
      - PYTHONPATH=.
      - CELERY_BROKER=pyamqp://rabbitmq:rabbitmq@rabbit//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbit
      - redis
  restaurant_service_asyncapi_docs_server:
    build:
      context: ./restaurant_service
      dockerfile: asyncapi_docs_server.Dockerfile
    command: http-server ./asyncapi_html
    ports:
      - "8083:8080"
  accounting_service_worker:
    build:
      context: .
      dockerfile: accounting_service/Dockerfile
      # note that context is project root folder, not service folder.
      #  It's done consciously because we need to copy app_common folder from project root
    environment:
      - PYTHONPATH=.
      - CELERY_BROKER=pyamqp://rabbitmq:rabbitmq@rabbit//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbit
      - redis
  accounting_service_asyncapi_docs_server:
    build:
      context: ./accounting_service
      dockerfile: asyncapi_docs_server.Dockerfile
    command: http-server ./asyncapi_html
    ports:
      - "8084:8080"
